### PR TITLE
Minor Fixes

### PR DESCRIPTION
**Pull request by Capkirk123**
Fix the Gemini Internal not working, and integrate the Orion HS into the capsule, due to occlusion calculations in KSP being very unreliable.

### CODE REVIEW

**Comment by lpgagnon** [comment]
gemini IVA looks good. crew might be a bit on the large side, but not worth fiddling with.
haven't tried the orion change

**Comment by Ilikeflyingplanes1** [comment]
small gap in between the heat shield and the sides of the capsule on the orion capsule

**Comment by Capkirk123** [comment]
> small gap in between the heat shield and the sides of the capsule on the orion capsule

The original model is like that, I can't really do anything about it



> gemini IVA looks good. crew might be a bit on the large side, but not worth fiddling with.
> haven't tried the orion change

The size of Kerbals in IVA randomly changes when you EVA/transfer crew, I don't think I can control it.

**Comment by DRVeyl** [comment]
Going to go ahead and merge this now.  Enough irritation with heatshields, and eventually we either will, or will not, remove heatshields from capsules overall.  This is just one more to that list.

Note: https://github.com/KSP-RO/RealismOverhaul/pull/2283 will at least help with consistent heatshield configurations across parts.  Even if capsules-as-heatshields remains a thing, we can move to that tool to improve things generally.

**Pull request merged**
