### PR TITLE
RN Soyuz-T (early), DECQ Soyuz-MS (modern) and SSVP Passive Docking Port

### PR DESCRIPTION
**Pull request by fdlp-e**
- Added Soyuz-T by RaiderNick for Soviet-era LEO missions
- Added Soyuz-MS by DECQ for modern Russian LEO crew transportation
- Added SSVP Docking Port so there is something to dock Soyuz with

### CODE REVIEW

**Comment by DRVeyl** [comment]
I've gotten the impression RN does not want any more of his assets moved into ROCapsules.

**Comment by fdlp-e** [comment]
Oh, okay, I may only leave DECQ Soyuz then.

**Comment by DRVeyl** [comment]
That would be fine.  If you strip this down to just the DECQ component, I believe we would merge that.

**Comment by DRVeyl** [comment]
Anyone get a chance to test this?  Been sitting here way too long.

**Comment by StonesmileGit** [comment]
- The physical parts seem to be correctly configured.

- Configs need to be reworked to be balanced with RO.

- Configs needs to be re-formatted to fit the formatting in the rest of ROCapsules.

**Comment by StonesmileGit** [comment]
Some additional findings from testing:

- Descent capsule missing HTPB for landing impact rockets.
Descent capsule has 50 ablator. Why?
Descent capsule resources - are they correct?

- Heatshield not in airstream, no ablator used.
Heatshield starts as "not staged".
Heatshield appears to float like a frisbee when jettisoned. Wrong mass or drag?

- Vzor telescope starts as "not staged".

- Service module has one RCS enabled, the other disabled in VAB. Is this correct?

- Orbital module resources - are they correct?
Orbital module starts of as not staged, yet has a staging icon; causes confusion.

- Docking system; Is there a female docking port?

- AKR antenna might be facing the wrong way when extended. (minor issue)
AKR antenna PAW says "extend panel" instead of "extend antenna".

**Comment by vader111** [comment]
I think we can close this and use my PR instead.
https://github.com/KSP-RO/ROCapsules/pull/68

**Comment by NathanKell** [comment]
RN isn't allowing parts to be cloned (we retain special dispensation for Vostok).

**Comment by NathanKell** [comment]
Ah, I missed that was discussed above, sorry! At any rate @Capkirk123 has some Soyuz plans so we're waiting on that.

**Pull request closed without merging**
