### PR TITLE
CLS Support

### PR DESCRIPTION
**Pull request by Capkirk123**
Restore CLS support to ROCapsules. Unfortunately, the Apollo Docking Ports and the Voskhod airlock do not function correctly with CLS, and register as impassable. The Voskhod docking port has been changed to surface-attach to fix it.

Requires https://github.com/KSP-RO/ROKerbalism/pull/126

### CODE REVIEW

**Comment by NathanKell** [comment]
(a) woo!!
(b) What's wrong with the Apollo port??

**Comment by Capkirk123** [comment]
The DECQ Apollo Ports (particularly the drogue port, both the standalone part and the LM) refuse to allow passage through their nodes. The Voskhod airlock had a similar problem, but that was more easily resolved. I _suspect_ the issue is related to both parts having unused transforms that are named like docking port transforms confusing CLS, but I don’t know enough to diagnose further.

**Comment by NathanKell** [comment]
Oh OK I thought you were talking about the BDB parts. Eh, don't care enough to spend time now since...DECQ. ;)

**Comment by Capkirk123** [comment]
Sure, but who knows what other parts we _do_ care about it might also effect. I'm gonna open an issue with CLS, at least.

**Pull request closed without merging**
