### PR TITLE
Fix up LEO & Lunar Heatshields. (Ready To Review)

### PR DESCRIPTION
**Pull request by vader111**
Fix up LEO & Lunar Heatshields.

### CODE REVIEW

**Comment by siimav** [comment]
The temps are supposed to come from RO heatshield templates
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_Heatshields.cfg#L20-L21

**Comment by vader111** [comment]
I have removed the Lunar Values, but have kept the LEO ones since i have found that those values keep the CM and Heatshield from going Kaboom

**Comment by siimav** [comment]
There's also https://github.com/KSP-RO/RealismOverhaul/pull/2366 which will once again turn the heating on it's head. Most of the ablator values are a lot more sane there but mass figures still need double checking against the references.

**Comment by vader111** [comment]
Should be good now

**Comment by vader111** [comment]
(Ready To Review)

**Comment by DRVeyl** [comment]
The changes look fine, except why are we deleting the Orion HS config file?

**Comment by vader111** [comment]
@DRVeyl is removed it because the PR hasn't been merged yet
https://github.com/KSP-RO/ROCapsules/pull/54

**Comment by DRVeyl** [comment]
Should not have touched it.  Removing it causes confusion at best; I've merged that PR, this conflicts because it now wants to delete something that was changed.  Please resolve the new conflict and I will merge this.

**Comment by vader111** [comment]
Git is SHIT

**Pull request closed without merging**
